### ISSUE TITLE
Use Dgraph database instead MySQL

### ISSUE THREAD

**Issue by zejiran** [zejiran/backend-simple-buyers-platform#1]
Change traditional database with new alternative native GraphQL database. 
- [Dgraph](https://dgraph.io/)
- [Dgraph Documentation](https://dgraph.io/docs/)

**Comment by dvshsahu** [comment]
Hi @zejiran can I take a look into the issue?

**Comment by zejiran** [comment]
@dvshsahu sure! You are welcome 🎉

**Comment by zejiran** [comment]
Hey @dvshsahu hope you are well. How is everything over there?

**Comment by dvshsahu** [comment]
Hi, @zejiran 'm doing good, How are you?
'M still working on the changes, I had to invest some time in going through the documentation of dgraph which took a bit of time.

**Comment by zejiran** [comment]
Nice! Thank you for your time.
